In [41]:
from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,OneHotEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix,roc_curve,auc,roc_auc_score
from sklearn.impute import KNNImputer 
from sklearn.linear_model import LogisticRegression

In [15]:
iris = datasets.load_iris()

In [16]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [17]:
x = pd.DataFrame(iris.data,columns=iris.feature_names)

In [49]:
# print(iris.target_names(), columns= 'categoty')

In [31]:
y = pd.DataFrame(iris.target, columns= ['categoty'])
y

     categoty
0           0
1           0
2           0
3           0
4           0
..        ...
145         2
146         2
147         2
148         2
149         2

[150 rows x 1 columns]

In [ ]:
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [32]:
x_train,x_test,y_train,y_test = train_test_split(x,y ,test_size=0.3,random_state=42)

In [33]:
log = LogisticRegression()
df = log.fit(x_train,y_train)

/home/prit.chavda@simform.dom/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [35]:
y_pre = log.predict(x_test)

In [37]:
accuracy_score(y_test,y_pre)

1.0

In [38]:
print("Classification Report:\n", classification_report(y_test, y_pre))

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45